export default [
  [
    {
      value: '`',
      title: '` ~',
      altValue: '~',
      className: 'dark Backquote',
    },
    {
      value: '1',
      title: '<sup>! </sup>1',
      altValue: '!',
      className: 'light Digit1',
    },
    {
      value: '2',
      title: '<sup>@ </sup>2',
      altValue: '@',
      className: 'light Digit2',
    },
    {
      value: '3',
      title: '<sup>#</sup>3',
      altValue: '# ',
      className: 'light Digit3',
    },
    {
      value: '4',
      title: '<sup>$ </sup>4',
      altValue: '$',
      className: 'light Digit4',
    },
    {
      value: '5',
      title: '<sup>% </sup>5',
      altValue: '%',
      className: 'light Digit5',
    },
    {
      value: '6',
      title: '<sup>^ </sup>6',
      altValue: '^',
      className: 'light Digit6',
    },
    {
      value: '7',
      title: '<sup>& </sup>7',
      altValue: '&',
      className: 'light Digit7',
    },
    {
      value: '8',
      title: '<sup>* </sup>8',
      altValue: '*',
      className: 'light Digit8',
    },
    {
      value: '9',
      title: '<sup>( </sup>9',
      altValue: '(',
      className: 'light Digit9',
    },
    {
      value: '0',
      title: '<sup>) </sup>0',
      altValue: ')',
      className: 'light Digit0',
    },
    {
      value: '-',
      title: '<sup>_ </sup>-',
      altValue: '_',
      className: 'light Minus',
    },
    {
      value: '=',
      title: '<sup>+</sup>=',
      altValue: '+',
      className: 'light Equal',
    },
    {
      value: 'Backspace',
      title: 'Backspace',
      altValue: 'Backspace',
      className: 'dark Backspace',
    },
  ],
  [
    {
      value: '&nbsp;&nbsp;&nbsp;&nbsp;',
      title: 'Tab',
      altValue: '&nbsp;&nbsp;&nbsp;&nbsp;',
      className: 'dark Tab',
    },
    {
      value: 'q',
      title: 'Q',
      altValue: 'Q',
      className: 'light KeyQ',
    },
    {
      value: 'w',
      title: 'W',
      altValue: 'W',
      className: 'light KeyW',
    },
    {
      value: 'e',
      title: 'E',
      altValue: 'E',
      className: 'light KeyE',
    },
    {
      value: 'r',
      title: 'R',
      altValue: 'R',
      className: 'light KeyR',
    },
    {
      value: 't',
      title: 'T',
      altValue: 'T',
      className: 'light KeyT',
    },
    {
      value: 'y',
      title: 'Y',
      altValue: 'Y',
      className: 'light KeyY',
    },
    {
      value: 'u',
      title: 'U',
      altValue: 'U',
      className: 'light KeyU',
    },
    {
      value: 'i',
      title: 'I',
      altValue: 'I',
      className: 'light KeyI',
    },
    {
      value: 'o',
      title: 'O',
      altValue: 'O',
      className: 'light KeyO',
    },
    {
      value: 'p',
      title: 'P',
      altValue: 'P',
      className: 'light KeyP',
    },
    {
      value: '[',
      title: '<sup>{ </sup>[',
      altValue: '{',
      className: 'light BracketLeft',
    },
    {
      value: ']',
      title: '<sup>} </sup>]',
      altValue: '}',
      className: 'light BracketRight',
    },
    {
      value: '\\',
      title: '<sup>/ </sup>\\',
      altValue: '/',
      className: 'light Backslash',
    },
    {
      value: 'Delete',
      title: 'DEL',
      altValue: 'Delete',
      className: 'dark Delete',
    },
  ],
  [
    {
      value: 'CapsLock',
      title: 'Caps Lock',
      altValue: 'CapsLock',
      className: 'dark CapsLock',
    },
    {
      value: 'a',
      title: 'A',
      altValue: 'A',
      className: 'light KeyA',
    },
    {
      value: 's',
      title: 'S',
      altValue: 'S',
      className: 'light KeyS',
    },
    {
      value: 'd',
      title: 'D',
      altValue: 'D',
      className: 'light KeyD',
    },
    {
      value: 'f',
      title: 'F',
      altValue: 'F',
      className: 'light KeyF',
    },
    {
      value: 'g',
      title: 'G',
      altValue: 'G',
      className: 'light KeyG',
    },
    {
      value: 'h',
      title: 'H',
      altValue: 'H',
      className: 'light KeyH',
    },
    {
      value: 'j',
      title: 'J',
      altValue: 'J',
      className: 'light KeyJ',
    },
    {
      value: 'k',
      title: 'K',
      altValue: 'K',
      className: 'light KeyK',
    },
    {
      value: 'l',
      title: 'L',
      altValue: 'L',
      className: 'light KeyL',
    },
    {
      value: ';',
      title: '<sup>: </sup>;',
      altValue: ':',
      className: 'light Semicolon',
    },
    {
      value: '\'',
      title: '<sup>" </sup>\'',
      altValue: '"',
      className: 'light Quote',
    },
    {
      value: '<br>',
      title: 'ENTER',
      altValue: '<br>',
      className: 'dark Enter',
    },
  ],
  [
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark ShiftLeft',
    },
    {
      value: '\'',
      title: '<sup>| </sup>\'',
      altValue: '|',
      className: 'light IntlBackslash',
    },
    {
      value: 'z',
      title: 'Z',
      altValue: 'Z',
      className: 'light KeyZ',
    },
    {
      value: 'x',
      title: 'X',
      altValue: 'X',
      className: 'light KeyX',
    },
    {
      value: 'c',
      title: 'C',
      altValue: 'C',
      className: 'light KeyC',
    },
    {
      value: 'v',
      title: 'V',
      altValue: 'V',
      className: 'light KeyV',
    },
    {
      value: 'b',
      title: 'B',
      altValue: 'B',
      className: 'light KeyB',
    },
    {
      value: 'n',
      title: 'N',
      altValue: 'N',
      className: 'light KeyN',
    },
    {
      value: 'm',
      title: 'M',
      altValue: 'M',
      className: 'light KeyM',
    },
    {
      value: ',',
      title: '<sup>< </sup>,',
      altValue: '<',
      className: 'light Comma',
    },
    {
      value: '.',
      title: '<sup>> </sup>.',
      altValue: '>',
      className: 'light Period',
    },
    {
      value: '/',
      title: '<sup>? </sup>/',
      altValue: '?',
      className: 'light Slash',
    },
    {
      value: '&#9650;',
      title: '&#9650;',
      altValue: '&#9650;',
      className: 'dark ArrowUp',
    },
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark ShiftRight',
    },
  ],
  [
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark ControlLeft',
    },
    {
      value: 'Win',
      title: 'Win',
      altValue: 'Win',
      className: 'dark MetaLeft',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark AltLeft',
    },
    {
      value: '&nbsp;',
      title: '',
      altValue: '&nbsp;',
      className: 'light Space',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark AltRight',
    },
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark ControlRight',
    },
    {
      value: '&#9668;',
      title: '&#9668;',
      altValue: '&#9668;',
      className: 'dark ArrowLeft',
    },
    {
      value: '&#9660;',
      title: '&#9660;',
      altValue: '&#9660;',
      className: 'dark ArrowDown',
    },
    {
      value: '&#9658;',
      title: '&#9658;',
      altValue: '&#9658;',
      className: 'dark ArrowRight',
    },
  ],
];
