export default [
  [
    {
      value: 'ё',
      title: 'Ё',
      altValue: 'Ё',
      className: 'dark Backquote',
    },
    {
      value: '1',
      title: '<sup>! </sup>1',
      altValue: '!',
      className: 'light Digit1',
    },
    {
      value: '2',
      title: '<sup>" </sup>2',
      altValue: '"',
      className: 'light Digit2',
    },
    {
      value: '3',
      title: '<sup>№ </sup>3',
      altValue: '№',
      className: 'light Digit3',
    },
    {
      value: '4',
      title: '<sup>; </sup>4',
      altValue: ';',
      className: 'light Digit4',
    },
    {
      value: '5',
      title: '<sup>% </sup>5',
      altValue: '%',
      className: 'light Digit5',
    },
    {
      value: '6',
      title: '<sup>: </sup>6',
      altValue: ':',
      className: 'light Digit6',
    },
    {
      value: '7',
      title: '<sup>? </sup>7',
      altValue: '?',
      className: 'light Digit7',
    },
    {
      value: '8',
      title: '<sup>* </sup>8',
      altValue: '*',
      className: 'light Digit8',
    },
    {
      value: '9',
      title: '<sup>( </sup>9',
      altValue: '(',
      className: 'light Digit9',
    },
    {
      value: '0',
      title: '<sup>) </sup>0',
      altValue: ')',
      className: 'light Digit0',
    },
    {
      value: '-',
      title: '<sup>_ </sup>-',
      altValue: '_',
      className: 'light Minus',
    },
    {
      value: '=',
      title: '<sup>+ </sup>=',
      altValue: '+',
      className: 'light Equal',
    },
    {
      value: 'Backspace',
      title: 'Backspace',
      altValue: 'Backspace',
      className: 'dark Backspace',
    },
  ],
  [
    {
      value: '&nbsp;&nbsp;&nbsp;&nbsp;',
      title: 'Tab',
      altValue: '&nbsp;&nbsp;&nbsp;&nbsp;',
      className: 'dark Tab',
    },
    {
      value: 'й',
      title: 'Й',
      altValue: 'Й',
      className: 'light KeyQ',
    },
    {
      value: 'ц',
      title: 'Ц',
      altValue: 'Ц',
      className: 'light KeyW',
    },
    {
      value: 'у',
      title: 'У',
      altValue: 'У',
      className: 'light KeyE',
    },
    {
      value: 'к',
      title: 'К',
      altValue: 'К',
      className: 'light KeyR',
    },
    {
      value: 'е',
      title: 'Е',
      altValue: 'Е',
      className: 'light KeyT',
    },
    {
      value: 'н',
      title: 'Н',
      altValue: 'Н',
      className: 'light KeyY',
    },
    {
      value: 'г',
      title: 'Г',
      altValue: 'Г',
      className: 'light KeyU',
    },
    {
      value: 'ш',
      title: 'Ш',
      altValue: 'Ш',
      className: 'light KeyI',
    },
    {
      value: 'щ',
      title: 'Щ',
      altValue: 'Щ',
      className: 'light KeyO',
    },
    {
      value: 'з',
      title: 'З',
      altValue: 'З',
      className: 'light KeyP',
    },
    {
      value: 'х',
      title: 'Х',
      altValue: 'Х',
      className: 'light BracketLeft',
    },
    {
      value: 'ъ',
      title: 'Ъ',
      altValue: 'Ъ',
      className: 'light BracketRight',
    },
    {
      value: '\\',
      title: '<sup>/ </sup>\\',
      altValue: '/',
      className: 'light Backslash',
    },
    {
      value: 'Delete',
      title: 'DEL',
      altValue: 'Delete',
      className: 'dark Delete',
    },
  ],
  [
    {
      value: 'CapsLock',
      title: 'Caps Lock',
      altValue: 'CapsLock',
      className: 'dark CapsLock',
    },
    {
      value: 'ф',
      title: 'Ф',
      altValue: 'Ф',
      className: 'light KeyA',
    },
    {
      value: 'ы',
      title: 'Ы',
      altValue: 'Ы',
      className: 'light KeyS',
    },
    {
      value: 'в',
      title: 'В',
      altValue: 'В',
      className: 'light KeyD',
    },
    {
      value: 'а',
      title: 'А',
      altValue: 'А',
      className: 'light KeyF',
    },
    {
      value: 'п',
      title: 'П',
      altValue: 'П',
      className: 'light KeyG',
    },
    {
      value: 'р',
      title: 'Р',
      altValue: 'Р',
      className: 'light KeyH',
    },
    {
      value: 'о',
      title: 'О',
      altValue: 'О',
      className: 'light KeyJ',
    },
    {
      value: 'л',
      title: 'Л',
      altValue: 'Л',
      className: 'light KeyK',
    },
    {
      value: 'д',
      title: 'Д',
      altValue: 'Д',
      className: 'light KeyL',
    },
    {
      value: 'ж',
      title: 'Ж',
      altValue: 'Ж',
      className: 'light Semicolon',
    },
    {
      value: 'э',
      title: 'Э',
      altValue: 'Э',
      className: 'light Quote',
    },
    {
      value: '<br>',
      title: 'ENTER',
      altValue: '<br>',
      className: 'dark Enter',
    },
  ],
  [
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark ShiftLeft',
    },
    {
      value: '\'',
      title: '<sup>/</sup>\'',
      altValue: '/',
      className: 'light IntlBackslash',
    },
    {
      value: 'я',
      title: 'Я',
      altValue: 'Я',
      className: 'light KeyZ',
    },
    {
      value: 'ч',
      title: 'Ч',
      altValue: 'Ч',
      className: 'light KeyX',
    },
    {
      value: 'с',
      title: 'С',
      altValue: 'С',
      className: 'light KeyC',
    },
    {
      value: 'м',
      title: 'М',
      altValue: 'М',
      className: 'light KeyV',
    },
    {
      value: 'и',
      title: 'И',
      altValue: 'И',
      className: 'light KeyB',
    },
    {
      value: 'т',
      title: 'Т',
      altValue: 'Т',
      className: 'light KeyN',
    },
    {
      value: 'ь',
      title: 'Ь',
      altValue: 'Ь',
      className: 'light KeyM',
    },
    {
      value: 'б',
      title: 'Б',
      altValue: 'Б',
      className: 'light Comma',
    },
    {
      value: 'ю',
      title: 'Ю',
      altValue: 'Ю',
      className: 'light Period',
    },
    {
      value: '.',
      title: '<sup>,</sup>.',
      altValue: ',',
      className: 'light Slash',
    },
    {
      value: '&#9650;',
      title: '&#9650;',
      altValue: '&#9650;',
      className: 'dark ArrowUp',
    },
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark ShiftRight',
    },
  ],
  [
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark ControlLeft',
    },
    {
      value: 'Win',
      title: 'Win',
      altValue: 'Win',
      className: 'dark MetaLeft',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark AltLeft',
    },
    {
      value: '&nbsp;',
      title: '',
      altValue: '&nbsp;',
      className: 'light Space',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark AltRight',
    },
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark ControlRight',
    },
    {
      value: '&#9668;',
      title: '&#9668;',
      altValue: '&#9668;',
      className: 'dark ArrowLeft',
    },
    {
      value: '&#9660;',
      title: '&#9660;',
      altValue: '&#9660;',
      className: 'dark ArrowDown',
    },
    {
      value: '&#9658;',
      title: '&#9658;',
      altValue: '&#9658;',
      className: 'dark ArrowRight',
    },
  ],
];
