export default [
  [
    {
      value: 'ё',
      title: 'Ё',
      altValue: 'Ё',
      className: 'dark',
    },
    {
      value: '1',
      title: '<sup>!</sup>1',
      altValue: '!',
      className: 'light',
    },
    {
      value: '2',
      title: '<sup>"</sup>2',
      altValue: '"',
      className: 'light',
    },
    {
      value: '3',
      title: '<sup>№</sup>3',
      altValue: '№',
      className: 'light',
    },
    {
      value: '4',
      title: '<sup>;</sup>4',
      altValue: ';',
      className: 'light',
    },
    {
      value: '5',
      title: '<sup>%</sup>5',
      altValue: '%',
      className: 'light',
    },
    {
      value: '6',
      title: '<sup>:</sup>6',
      altValue: ':',
      className: 'light',
    },
    {
      value: '7',
      title: '<sup>?</sup>7',
      altValue: '?',
      className: 'light',
    },
    {
      value: '8',
      title: '<sup>*</sup>8',
      altValue: '*',
      className: 'light',
    },
    {
      value: '9',
      title: '<sup>(</sup>9',
      altValue: '(',
      className: 'light',
    },
    {
      value: '0',
      title: '<sup>)</sup>0',
      altValue: ')',
      className: 'light',
    },
    {
      value: '-',
      title: '<sup>_</sup>-',
      altValue: '_',
      className: 'light',
    },
    {
      value: '=',
      title: '<sup>+</sup>=',
      altValue: '+',
      className: 'light',
    },
    {
      value: 'Backspace',
      title: 'Backspace',
      altValue: 'Backspace',
      className: 'dark',
    },
  ],
  [
    {
      value: '&nbsp;&nbsp;&nbsp;&nbsp;',
      title: 'Tab',
      altValue: '&nbsp;&nbsp;&nbsp;&nbsp;',
      className: 'dark',
    },
    {
      value: 'й',
      title: 'Й',
      altValue: 'Й',
      className: 'light',
    },
    {
      value: 'ц',
      title: 'Ц',
      altValue: 'Ц',
      className: 'light',
    },
    {
      value: 'у',
      title: 'У',
      altValue: 'У',
      className: 'light',
    },
    {
      value: 'к',
      title: 'К',
      altValue: 'К',
      className: 'light',
    },
    {
      value: 'е',
      title: 'Е',
      altValue: 'Е',
      className: 'light',
    },
    {
      value: 'н',
      title: 'Н',
      altValue: 'Н',
      className: 'light',
    },
    {
      value: 'г',
      title: 'Г',
      altValue: 'Г',
      className: 'light',
    },
    {
      value: 'ш',
      title: 'Ш',
      altValue: 'Ш',
      className: 'light',
    },
    {
      value: 'щ',
      title: 'Щ',
      altValue: 'Щ',
      className: 'light',
    },
    {
      value: 'з',
      title: 'З',
      altValue: 'З',
      className: 'light',
    },
    {
      value: 'х',
      title: 'Х',
      altValue: 'Х',
      className: 'light',
    },
    {
      value: 'ъ',
      title: 'Ъ',
      altValue: 'Ъ',
      className: 'light',
    },
    {
      value: '\\',
      title: '<sup>/</sup>\\',
      altValue: '/',
      className: 'light',
    },
    {
      value: 'Delete',
      title: 'DEL',
      altValue: 'Delete',
      className: 'dark',
    },
  ],
  [
    {
      value: 'CapsLock',
      title: 'Caps Lock',
      altValue: 'CapsLock',
      className: 'dark',
    },
    {
      value: 'ф',
      title: 'Ф',
      altValue: 'Ф',
      className: 'light',
    },
    {
      value: 'ы',
      title: 'Ы',
      altValue: 'Ы',
      className: 'light',
    },
    {
      value: 'в',
      title: 'В',
      altValue: 'В',
      className: 'light',
    },
    {
      value: 'а',
      title: 'А',
      altValue: 'А',
      className: 'light',
    },
    {
      value: 'п',
      title: 'П',
      altValue: 'П',
      className: 'light',
    },
    {
      value: 'р',
      title: 'Р',
      altValue: 'Р',
      className: 'light',
    },
    {
      value: 'о',
      title: 'О',
      altValue: 'О',
      className: 'light',
    },
    {
      value: 'л',
      title: 'Л',
      altValue: 'Л',
      className: 'light',
    },
    {
      value: 'д',
      title: 'Д',
      altValue: 'Д',
      className: 'light',
    },
    {
      value: 'ж',
      title: 'Ж',
      altValue: 'Ж',
      className: 'light',
    },
    {
      value: 'э',
      title: 'Э',
      altValue: 'Э',
      className: 'light',
    },
    {
      value: '<br>',
      title: 'ENTER',
      altValue: '<br>',
      className: 'dark',
    },
  ],
  [
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark',
    },
    {
      value: '\'',
      title: '<sup>/</sup>\'',
      altValue: '/',
      className: 'light',
    },
    {
      value: 'я',
      title: 'Я',
      altValue: 'Я',
      className: 'light',
    },
    {
      value: 'ч',
      title: 'Ч',
      altValue: 'Ч',
      className: 'light',
    },
    {
      value: 'с',
      title: 'С',
      altValue: 'С',
      className: 'light',
    },
    {
      value: 'м',
      title: 'М',
      altValue: 'М',
      className: 'light',
    },
    {
      value: 'и',
      title: 'И',
      altValue: 'И',
      className: 'light',
    },
    {
      value: 'т',
      title: 'Т',
      altValue: 'Т',
      className: 'light',
    },
    {
      value: 'ь',
      title: 'Ь',
      altValue: 'Ь',
      className: 'light',
    },
    {
      value: 'б',
      title: 'Б',
      altValue: 'Б',
      className: 'light',
    },
    {
      value: 'ю',
      title: 'Ю',
      altValue: 'Ю',
      className: 'light',
    },
    {
      value: '.',
      title: '<sup>,</sup>.',
      altValue: ',',
      className: 'light',
    },
    {
      value: '&#9650;',
      title: '&#9650;',
      altValue: '&#9650;',
      className: 'dark',
    },
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark',
    },
  ],
  [
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark',
    },
    {
      value: 'Win',
      title: 'Win',
      altValue: 'Win',
      className: 'dark',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark',
    },
    {
      value: '&nbsp;',
      title: '',
      altValue: '&nbsp;',
      className: 'light',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark',
    },
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark',
    },
    {
      value: '&#9668;',
      title: '&#9668;',
      altValue: '&#9668;',
      className: 'dark',
    },
    {
      value: '&#9660;',
      title: '&#9660;',
      altValue: '&#9660;',
      className: 'dark',
    },
    {
      value: '&#9658;',
      title: '&#9658;',
      altValue: '&#9658;',
      className: 'dark',
    },
  ],
];
