export default [
  [
    {
      value: '`',
      title: '`~',
      altValue: '~',
      className: 'dark',
    },
    {
      value: '1',
      title: '<sup>!</sup>1',
      altValue: '!',
      className: 'light',
    },
    {
      value: '2',
      title: '<sup>@</sup>2',
      altValue: '@',
      className: 'light',
    },
    {
      value: '3',
      title: '<sup>#</sup>3',
      altValue: '#',
      className: 'light',
    },
    {
      value: '4',
      title: '<sup>$</sup>4',
      altValue: '$',
      className: 'light',
    },
    {
      value: '5',
      title: '<sup>%</sup>5',
      altValue: '%',
      className: 'light',
    },
    {
      value: '6',
      title: '<sup>^</sup>6',
      altValue: '^',
      className: 'light',
    },
    {
      value: '7',
      title: '<sup>&</sup>7',
      altValue: '&',
      className: 'light',
    },
    {
      value: '8',
      title: '<sup>*</sup>8',
      altValue: '*',
      className: 'light',
    },
    {
      value: '9',
      title: '<sup>(</sup>9',
      altValue: '(',
      className: 'light',
    },
    {
      value: '0',
      title: '<sup>)</sup>0',
      altValue: ')',
      className: 'light',
    },
    {
      value: '-',
      title: '<sup>_</sup>-',
      altValue: '_',
      className: 'light',
    },
    {
      value: '=',
      title: '<sup>+</sup>=',
      altValue: '+',
      className: 'light',
    },
    {
      value: 'Backspace',
      title: 'Backspace',
      altValue: 'Backspace',
      className: 'dark',
    },
  ],
  [
    {
      value: '&nbsp;&nbsp;&nbsp;&nbsp;',
      title: 'Tab',
      altValue: '&nbsp;&nbsp;&nbsp;&nbsp;',
      className: 'dark',
    },
    {
      value: 'q',
      title: 'Q',
      altValue: 'Q',
      className: 'light',
    },
    {
      value: 'w',
      title: 'W',
      altValue: 'W',
      className: 'light',
    },
    {
      value: 'e',
      title: 'E',
      altValue: 'E',
      className: 'light',
    },
    {
      value: 'r',
      title: 'R',
      altValue: 'R',
      className: 'light',
    },
    {
      value: 't',
      title: 'T',
      altValue: 'T',
      className: 'light',
    },
    {
      value: 'y',
      title: 'Y',
      altValue: 'Y',
      className: 'light',
    },
    {
      value: 'u',
      title: 'U',
      altValue: 'U',
      className: 'light',
    },
    {
      value: 'i',
      title: 'I',
      altValue: 'I',
      className: 'light',
    },
    {
      value: 'o',
      title: 'O',
      altValue: 'O',
      className: 'light',
    },
    {
      value: 'p',
      title: 'P',
      altValue: 'P',
      className: 'light',
    },
    {
      value: '[',
      title: '<sup>{</sup>[',
      altValue: '{',
      className: 'light',
    },
    {
      value: ']',
      title: '<sup>}</sup>]',
      altValue: '}',
      className: 'light',
    },
    {
      value: '\\',
      title: '<sup>/</sup>\\',
      altValue: '/',
      className: 'light',
    },
    {
      value: 'Delete',
      title: 'DEL',
      altValue: 'Delete',
      className: 'dark',
    },
  ],
  [
    {
      value: 'CapsLock',
      title: 'Caps Lock',
      altValue: 'CapsLock',
      className: 'dark',
    },
    {
      value: 'a',
      title: 'A',
      altValue: 'A',
      className: 'light',
    },
    {
      value: 's',
      title: 'S',
      altValue: 'S',
      className: 'light',
    },
    {
      value: 'd',
      title: 'D',
      altValue: 'D',
      className: 'light',
    },
    {
      value: 'f',
      title: 'F',
      altValue: 'F',
      className: 'light',
    },
    {
      value: 'g',
      title: 'G',
      altValue: 'G',
      className: 'light',
    },
    {
      value: 'h',
      title: 'H',
      altValue: 'H',
      className: 'light',
    },
    {
      value: 'j',
      title: 'J',
      altValue: 'J',
      className: 'light',
    },
    {
      value: 'k',
      title: 'K',
      altValue: 'K',
      className: 'light',
    },
    {
      value: 'l',
      title: 'L',
      altValue: 'L',
      className: 'light',
    },
    {
      value: ';',
      title: '<sup>:</sup>;',
      altValue: ':',
      className: 'light',
    },
    {
      value: '\'',
      title: '<sup>"</sup>\'',
      altValue: '"',
      className: 'light',
    },
    {
      value: '<br>',
      title: 'ENTER',
      altValue: '<br>',
      className: 'dark',
    },
  ],
  [
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark',
    },
    {
      value: '\'',
      title: '<sup>|</sup>\'',
      altValue: '|',
      className: 'light',
    },
    {
      value: 'z',
      title: 'Z',
      altValue: 'Z',
      className: 'light',
    },
    {
      value: 'x',
      title: 'X',
      altValue: 'X',
      className: 'light',
    },
    {
      value: 'c',
      title: 'C',
      altValue: 'C',
      className: 'light',
    },
    {
      value: 'v',
      title: 'V',
      altValue: 'V',
      className: 'light',
    },
    {
      value: 'b',
      title: 'B',
      altValue: 'B',
      className: 'light',
    },
    {
      value: 'n',
      title: 'N',
      altValue: 'N',
      className: 'light',
    },
    {
      value: 'm',
      title: 'M',
      altValue: 'M',
      className: 'light',
    },
    {
      value: ',',
      title: '<sup><</sup>,',
      altValue: '<',
      className: 'light',
    },
    {
      value: '.',
      title: '<sup>></sup>.',
      altValue: '>',
      className: 'light',
    },
    {
      value: '/',
      title: '<sup>?</sup>/',
      altValue: '?',
      className: 'light',
    },
    {
      value: '&#9650;',
      title: '&#9650;',
      altValue: '&#9650;',
      className: 'dark',
    },
    {
      value: 'Shift',
      title: 'Shift',
      altValue: 'Shift',
      className: 'dark',
    },
  ],
  [
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark',
    },
    {
      value: 'Win',
      title: 'Win',
      altValue: 'Win',
      className: 'dark',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark',
    },
    {
      value: '&nbsp;',
      title: '',
      altValue: '&nbsp;',
      className: 'light',
    },
    {
      value: 'Alt',
      title: 'Alt',
      altValue: 'Alt',
      className: 'dark',
    },
    {
      value: 'Control',
      title: 'Ctrl',
      altValue: 'Control',
      className: 'dark',
    },
    {
      value: '&#9668;',
      title: '&#9668;',
      altValue: '&#9668;',
      className: 'dark',
    },
    {
      value: '&#9660;',
      title: '&#9660;',
      altValue: '&#9660;',
      className: 'dark',
    },
    {
      value: '&#9658;',
      title: '&#9658;',
      altValue: '&#9658;',
      className: 'dark',
    },
  ],
];
